- hosts:  UAT-servers
  tasks:
    - name: log into docker hub registry
      shell: docker login -u santu458 -p dckr_pat_u065r_4Qrq4CojzPVCPZh4LUQ8w
    - name: Pull the image from docker hub
      shell: docker pull santu458/santuproject099:{{BUILD_NUMBER}}
    - name: Run the container using the Image
      shell: docker run --name=santuapp01 -p 8080:8080 --detach santu458/santuproject099:{{BUILD_NUMBER}}
