apiVersion: v1
kind: Service
metadata:
  name: santuapp
spec:
  ports:
    - port: 8080
      nodePort: 30334
      targetPort: santuapp-port
      protocol: TCP
  selector:
    app: santuapp
  type: NodePort
