apiVersion: apps/v1
kind: Deployment
metadata:
  name: santudb
  labels:
    app:  santudb
spec:
  selector:
    matchLabels:
      app:  santudb
  replicas: 1
  template:
    metadata:
      labels: 
        app:  santudb
    spec:
      containers:
        - name: santudb
          image: santu458/santudb099:V1 
          volumeMounts:
            - mountPath:  /var/lib/mysql
              name: santudbvol
          ports:
            - name: santudb-port
              containerPort:  3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:  
                secretKeyRef:
                  name: app-secret
                  key:  dbpass
      nodeSelector:
        zone: santunode1
      volumes:
        - name: santudbvol
          hostPath:
            path: /data
            type: DirectoryOrCreate
