apiVersion: apps/v1
kind: Deployment
metadata:
  name: santuapp
  labels:
    app:  santuapp
spec:
  selector:
    matchLabels:
      app: santuapp 
  replicas: 1
  template:
    metadata:
      labels: 
        app: santuapp 
    spec:
      containers:
        - name: santuapp
          image: {{ .Values.app.image}}
          ports:
            - name: santuapp-port
              containerPort: 8080
