apiVersion: apps/v1
kind: Deployment
metadata:
  name: santurmq
  labels:
    app: santurmq 
spec:
  selector:
    matchLabels:
      app:  santurmq
  replicas: 1
  template:
    metadata:
      labels: 
        app:  santurmq
    spec:
      containers:
        - name: santurmq
          image: rabbitmq 
          ports:
            - name: santurmq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
             - name: RABBITMQ_DEFAULT_PASS
               value: "guest"
